### ISSUE TITLE
PCAP_NETMASK_UNKNOWN error when run on SLES 11 x86_64

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.network#10]
I have an application that uses the PacketFileSource operator to read from a PCAP file. When running this application on SLES 11 x86_64, the following error is returned: 

  [sc main] src/operator/PacketFileSource_4_245.cpp: In member function ‘void SPL::_Operator::PacketFileSource_4_245$OP::_processPCAPfile(std::string)_’:
  [sc main] src/operator/PacketFileSource_4_245.cpp:200: error: **‘PCAP_NETMASK_UNKNOWN’ was not declared in this scope**
...
  [sc main] make: **\* [build/operator/PacketFileSource_4_245.o] Error 1

**Comment by ejpring** [comment]
That symbol is defined in '/usr/include/pcap/pcap.h', starting with libpcap version 1.1, so I'm guessing that your SLES system has libpcap version 1.0 or earlier, from 2008 or earlier. Please execute this command to confirm that:

rpm -qa | grep libpcap

Whatever the version, was libpcap installed along with the rest of SLES from its distribution media, or separately from htp://tcpdump.org, or maybe from https://github.com/the-tcpdump-group/libpcap/ ?

-- Ed

**Comment by ejpring** [comment]
Never mind. According to 

https://www.suse.com/LinuxPackages/packageRouter.jsp?product=server&version=11&architecture=i386&package_name=index_all

SLES 11 includes libpcap version 0.9.8 , from 2007. 

This particular problem is easy enough to fix -- the symbol's value is 0xFFFFFFFF -- but I'm not confident that the rest of the operator will work with a version of libpcap that old.

I'd prefer to ask customers to upgrade to the latest version of libpcap. There are instructions in the documentation for that.

But if you really want to try with libpcap 0.9, I'll replace the symbol with its value ...

**Comment by cancilla** [comment]
Thanks Ed. I'll get the environment updated to the latest version. 

Do we have any docs indicating the minimum version of libpcap that should be installed? If not, can we add this to one of the README files for now?

**Comment by ejpring** [comment]
Sigh ...

No, I've never tried to choose a minimum version of libpcap. Instead, I've tested the PFS and PLS operators with each version that's bundled with some [but not all] RHEL/CentOS distributions, and with the some [but not all] versions available from http://tcpdump.org .  There's a table in the documentation:

This operator has been tested with these versions of 'libpcap':

```
libpcap 0.9.4, included in RHEL/CentOS 5.x
libpcap 1.0.0, included in RHEL/CentOS 6.2
libpcap 1.4.0, included in RHEL/CentOS 6.5
libpcap 1.5.3, included in RHEL/CentOS 7.1
libpcap 1.6.1
libpcap 1.6.2
libpcap 1.7.4
```

I can add " libpcap 0.9.8 / SLES 11 " to the table if you find it works with 0xFFFFFFFF substituted for PCAP_NETMASK_UNKNOWN ...

**Comment by ejpring** [comment]
I've changed PCAP_NETMASK_UNKNOWN to 0xFFFFFFFF in PFS, and issued a pull request. There are also changes to the parser classes to indicate which members are public and which are private, and more comments ...

**Comment by cancilla** [comment]
This fixed the issue. Thank you!

**Comment by ejpring** [comment]
OK, I'll add " libpcap 0.9.8 / SLES 11 " to the documentation.  Thanks for testing this.
