### ISSUE TITLE
liveDHCPMessageParserBasic.sh does not work

### ISSUE THREAD

**Issue by GudrunKa** [IBMStreams/streamsx.network#101]
In order to execute the liveDHCPMessageParserBasic.sh script, the xterm, socat and nmap-ncat rpms have to be installed. This is nowhere described. After the installation of these packages the script still does not work since the ncat connection to the leasePort is refused.

**Comment by GudrunKa** [comment]
Please update the documentation.

**Comment by ejpring** [comment]
The liveDHCPMessageParserBasic.sh script does depend upon the xterm and ncat commands, and has been updated to print an error message if they are not available.

The liveDHCPMessageParserBasic.sh script does not depend upon the socat command.

The liveDHCPMessageParserBasic.sh script starts the ncat command before starting the DHCPMessageParserBasic sample application, so the xterm window will display "Ncat: connection refused" once per second until the DHCPMessageParserBasic sample application initializes. Then the xterm window will display any DHCP messages received by the network interface. Note that servers with fixed IP addresses do not receive any DHCP messages, and laptops with dynamic IP addresses receive DHCP messages only when they connect to a wired or wireless network.
