### ISSUE TITLE
sample liveDNSMessageParserERSPAN hangs during/after PE shutdown

### ISSUE THREAD

**Issue by GudrunKa** [IBMStreams/streamsx.network#105]
When executing the script liveDNSMessageParserERSPAN.standalone.sh, the script does not come to an end. It remains in state: 
"spl_pe M[PEImpl.cpp:shutdown:1548]  - Exit PEImpl::shutdown()"

**Comment by markheger** [comment]
script does no longer exist in 3.0.3
