### ISSUE TITLE
Should RTP Processing Operators be a part of Network Toolkit instead of Speech2Text? 

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.network#125]
For our Speech2Text Call Center solution, we have built RTPDecode, RTPExtract, and RTPFilter operators for processing RTP packets to prepare network data for speech processing. 

The code for these operators can be view [here](https://github.com/IBMStreams/streamsx.speech2text/tree/master/applications/CallCenter/com.ibm.streamsx.speech2text.speechprocessing/com.ibm.streamsx.speech2text.speechprocessing.setup). 

Would it make sense to incorporate these operators into the network toolkit?

**Comment by ejpring** [comment]
Maybe. What do they do?

**Comment by engebret** [comment]
My view is they should go in this toolkit as it is just another network protocol.

**Comment by markheger** [comment]
I agree to Dave. But the operator need a description and there should be samples provided in the same format as the other streamsx.network toolkit samples, e.g. with "autotest scripts".

**Comment by Alex-Cook4** [comment]
@ejpring Here is a short summary of what they do: 
1. **RTPFilter** - Only forwards packets that meet the specific RTP protocol, version, and G711 audio requirements. This would probably want to be extended to take the version as a parameter, as well as the waveform codec (i.e. G729). 
2. **RTPExtract** - Extracts the RTP payload and length from the incoming packet. Currently, breaks down the header as well, but doesn't forward (could easily be changed to also forward). 
3. **RTPDecode** - Converts the G711 audio format to uncompressed 16-bit little endian audio for consumption by the WatsonS2T operator using a MuLaw decode.

**Comment by Alex-Cook4** [comment]
Given the need for samples and autotest scripts, plus the fact that I think these operators need significant enhancement before becoming part of a product toolkit, **would it make sense to create a development branch for these features to be developed in?** The branch would be something like: v3.0_RTP_dev

This would make sure that this code ends up in the right place long-term, without hurting the standard of the network toolkit in the meantime.

**Comment by ejpring** [comment]
I think it makes sense to do development work on a separate branch. I don't think you should include a version number in the branch name. How about just 'rtp-dev'?

**Comment by Alex-Cook4** [comment]
rtp-dev sounds good. Could someone please create that as a branch off of master, then I can create a pull request against that branch?

**Comment by ejpring** [comment]
Done.

**Comment by Alex-Cook4** [comment]
Thanks @ejpring, I am working locally on my own fork of that branch. I'm going to close this issue and open new issues related to how I should proceed to fit your standards.
