### ISSUE TITLE
DPDK Packet Drop Rate on MLX NIC is always 0

### ISSUE THREAD

**Issue by engebret** [IBMStreams/streamsx.network#128]
The packet drop rate reported by the DPDKSource operator always returns 0 on Mellanox CX3 NICs.

**Comment by ejpring** [comment]
Just to be clear, do you mean the 'ierrors' field in the 'rte_eth_stats' structure returned by the rte_eth_stats_get() function is not set by the Mellanox DPDK driver, or we haven't driven a Mellanox adapter hard enough for it to drop packets?

**Comment by engebret** [comment]
A fix has been checked into the DPDK shim to use the imissed field for drops.  This now works correctly on an Intel x520 NIC.  Note that for Mellanox the driver does not return values we can use for these stats (see http://dpdk.org/doc/guides/nics/mlx4.html  Section 18.3 Limitations).  My virtual e1000 also does not report drops.  Given the x520 works and we understand the MLX numbers now, I'm going to close this issue.
