### ISSUE TITLE
DPDKSource Update to DPDK version 16

### ISSUE THREAD

**Issue by engebret** [IBMStreams/streamsx.network#129]
Forward port to the current LTS version of 16 is required for currency.

**Comment by ejpring** [comment]
Might want to consider porting to version 17.05 instead. The release notes mention some PowerPC-related improvements: http://dpdk.org/doc/guides/rel_notes/release_17_05.html

**Comment by engebret** [comment]
We decided to focus the port on 17.02 as that is the current stable release.  The code is now working on an e1000/x86 system as well as a MLX-CX3/x86 system.  Changes were pretty minimal, and will require documentation updates.  I think we also need to add a mechanism to archive all the dpdk object files into one file & locate it in the network toolkit impl/lib directory, probably as part of the streams_source shim library build.

**Comment by engebret** [comment]
Forward port has been completed, so I'm closing this issue.
