### ISSUE TITLE
Namespace for RTP operators?

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.network#133]
What would be the best location for these new operators? A new namespace solely around RTP? 

1. **RTPFilter** - Only forwards packets that meet the specific RTP protocol, version, and G711 audio requirements. This would probably want to be extended to take the version as a parameter, as well as the waveform codec (i.e. G729). 
2. **RTPExtract** - Extracts the RTP payload and length from the incoming packet. Currently, breaks down the header as well, but doesn't forward (could easily be changed to also forward). 
3. **RTPDecode** - Converts the G711 audio format to uncompressed 16-bit little endian audio for consumption by the WatsonS2T operator using a MuLaw decode. 

As a new contributor, I don't want to mess up any standards that you guys would like to maintain.

**Comment by ejpring** [comment]
Yes, 'com.ibm.streamsx.network.rtp' would be the obvious choice for a new namespace, so I would go with that.
