### ISSUE TITLE
Testing PacketLiveSource in application? 

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.network#140]
I would like to test sending data through my PacketLiveSource operator listening on eth1. Can someone recommend the easiest way for me send the packets I want to eth1 on my local machine from my local machine? Ideally using Streams, but not necessarily.

**Comment by engebret** [comment]
Couple options that might work for you:
1. Use PacketFileSource and just read in the pcap file.
2. Use a pair of VMs on your local machine, one running the app and reading data off a 2nd virtual NIC, the other using tcpreplay to send the pcap data into a virtual NIC on that VM.  Tie the two NICs together on the same virtual switch that is separate from the normal LAN you are connected to.

**Comment by ejpring** [comment]
I don't think its necessary to use virtual machines if you're running the Streams application containing PacketLiveSource on a real machine. PLS should receive copies of every packet that goes in and out of the eth1 interface; at least, it does on the machines I use for testing PLS. You could verify that by running a web browser. If PLS sees that HTTP traffic, then it should also see whatever traffic you send into eth1 with the 'tcpreplay' utility. Of course, the replayed traffic could be resent to other machines, depending upon how its configured, so you wouldn't want to overdo this.

**Comment by Alex-Cook4** [comment]
Excellent. Thank you for the tips.
