### ISSUE TITLE
where are the streamsx.network images after 2.8.5?

### ISSUE THREAD

**Issue by just4li** [IBMStreams/streamsx.network#184]
Wondering what is the reason no toolkit images have been published after 2.8.5? 
We build our streams sab file using travis. Always download the toolkit images, such as streamsx.iot, streamsx.jdbc from IBMStreams site before the build inside an container.  All the other toolkits we are using provides updated images..

**Comment by markheger** [comment]
A "pre-built" release was not requested since most users use the toolkit shipped with the product or have built the toolkit.
3.0.9 has been released with for RH6 and RH7.
