### ISSUE TITLE
Generalize repository name to streamsx.network

### ISSUE THREAD

**Issue by engebret** [IBMStreams/streamsx.network#2]
In order to support the direction to include the base ingest & packet parsing level code in this repository, the name streamsx.network would be more appropriate than networkAnalysis.  The intent is to cover analysis level functions with other toolkits.

**Comment by cancilla** [comment]
+1

**Comment by chanskw** [comment]
+1

**Comment by cancilla** [comment]
Closing. Renaming to streamsx.network.

**Comment by chanskw** [comment]
Need to do a couple of more updates... reopening to keep track

**Comment by chanskw** [comment]
closing... done
