### ISSUE TITLE
Add @ejpring as committer

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.network#26]
I would like to propose that @ejpring be added as a committer for the streamsx.network repository. He is an active member of the community and is the primary contributer on this repository.

**Comment by petenicholls** [comment]
+1

**Comment by chanskw** [comment]
+1

**Comment by mikespicer** [comment]
+1

**Comment by ddebrunner** [comment]
+1

**Comment by engebret** [comment]
+1

**Comment by chanskw** [comment]
Added Ed as committer.  Welcome!
