### ISSUE TITLE
IPAddressLocation operator needs to support dynamic loading of MaxMind database

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.network#32]
The IPAddressLocation operator needs to support the ability to load in new versions of the MaxMind database whenever there is an update. This functionality needs to happen dynamically, without restarting the application. This was a important requirement when the IPSpatialEnricher operator was developed.

**Comment by cancilla** [comment]
any updates on this?

**Comment by ejpring** [comment]
Not yet. Maybe after the shell toolkit is finished.

**Comment by markheger** [comment]
A new optional control port needs to be added to accept the filename in a control tuple like IPSpatialEnricher operator
