### ISSUE TITLE
Missing SPLDOC comment in com.ibm.streamsx.network.enrichment/IPSpatialTypes.spl

### ISSUE THREAD

**Issue by conglisc** [IBMStreams/streamsx.network#33]
type IPASNumber_t and IPASNInfo_t do not have SPLDOC comment

**Comment by kanduibm** [comment]
I added the missing documentation for these two types and have already initialized a pull request. 

Thanks

**Comment by markheger** [comment]
merged on Jul 28, 2016, hence issue is closed.
