### ISSUE TITLE
IPAddressLocation needs to be capable of ingesting lists and matrices of IP addresses

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.network#34]
The IPAddressLocation operator needs to be capable of ingesting and enriching lists (SPL::list<T>) and matrices (SPL::listSPL::list<T>) of IP addresses. 

Here is the use case from the cybersecurity applications:
When parsing DNS messages, lists of IP addresses are returned for the answerData and the additionalData. All of these IP addresses need to be enriched before being sent downstream.

**Comment by cancilla** [comment]
any updates on this?

**Comment by markheger** [comment]
workaround with schema transformation in Custom operator possible
