### ISSUE TITLE
Problems building DPDK library

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.network#52]
There are some problems with the DPDK build instructions. 

1)

```
COMBINE_LIBS=y
LIBRTE_MLX4_PMD=y (MLX4 NIC)
```

should be:

```
CONFIG_RTE_BUILD_COMBINE_LIBS=y
CONFIG_RTE_LIBRTE_MLX4_PMD=y (MLX4 NIC)
```

2)

```
# Complete the build
make install T=x86_64-native-linuxapp-gcc
   OR
make install T=ppc_64-power8-linuxapp-gcc
```

finishes (fails?) with the following error:
**`Installation cannot run with T defined and DESTDIR undefined`**

3)
Building the "glue" code does not work. Running `make` from `/toolkit-directory/com.ibm.streamsx.network/impl/src/source/dpdk`
results in this error:

**`/home/cancilla/git/streamsx.network/dpdk-src/dpdk-2.2.0/mk/internal/rte.extvars.mk:57: *** Cannot find .config in /home/cancilla/git/streamsx.network/dpdk-src/dpdk-2.2.0.  Stop.`**

**Comment by cancilla** [comment]
**.bashrc**:

```
## DPDK
export EXTRA_CFLAGS=-fPIC
export RTE_SDK=/home/cancilla/git/streamsx.network/dpdk-src/dpdk-2.2.0
export RTE_TARGET=ppc_64-default-linuxapp-gcc
```

**Comment by kanduibm** [comment]
Hi James. I agree that the doc for config the env part should be updated.  Here is the updated steps and issues encountered so far. 

NIC
10:00.0 Ethernet controller: Broadcom Corporation NetXtreme II BCM5709S Gigabit Ethernet (rev 20)
10:00.1 Ethernet controller: Broadcom Corporation NetXtreme II BCM5709S Gigabit Ethernet (rev 20)
1. 
   download the dpdk source 
2. Set env var  (for example)  
   export EXTRA_CFLAGS=-fPIC
   export RTE_SDK=/homes/hny7/kandu/Downloads/dpdk-2.2.0
   export RTE_TARGET=x86_64-native-linuxapp-gcc
3. under ../Downloads/dpdk-2.2.0
   make config T=x86_64-native-linuxapp-gcc.
   This will generate the build dir
4. edit build/.config
   to build the shared lib lbdpdk.a I only need to set "CONFIG_RTE_BUILD_COMBINE_LIBS=y".
   CONFIG_RTE_FORCE_INTRINSICS=n
   Machine forces strict alignment constraints.
   CONFIG_RTE_ARCH_STRICT_ALIGN=n
   Compile to share library
   CONFIG_RTE_BUILD_SHARED_LIB=n  
   Combine to one single library
   CONFIG_RTE_BUILD_COMBINE_LIBS=y  
   Use newest code breaking previous ABI
   CONFIG_RTE_NEXT_ABI=y
   Compile Environment Abstraction Layer
5. Build the library from the parent directory (../Downloads/dpdk-2.2.0)
   make
6. Complete the install  by running "make install DESTDIR=dpdk-install T=x86_64-native-linuxapp-gcc. "
   make install T=x86_64-native-linuxapp-gcc
   Note 
   Make install at the end will complain that a destination directory does not exist If you do not explicitly specify the DESTDIR. Providing a DESTDIR path will resolve that issue. 
   make install DESTDIR=dpdk-install T=x86_64-native-linuxapp-gcc. 
   The default DESTDIR  "x86_64-native-linuxapp-gcc" will be created if you do not specify one.  
7. Copy lib to the toolkit. 
- cp build/lib/libdpdk.a /toolkit-directory/com.ibm.streamsx.network/impl/lib/source/
-  build Streams to DPDK glue library
-  cd /toolkit-directory/com.ibm.streamsx.network/impl/src/source/dpdk
-  make
- cp streams_source.h /toolkit-directory/com.ibm.streamsx.network/impl/include/source/
-  cp build/lib/libstreams_source.a /toolkit-directory/com.ibm.streamsx.network/impl/lib/source/
-  Note : 
-  streams_source.h should be copied to the "/toolkit-directory/com.ibm.streamsx.network/impl//include/source/" not  ../impl/lib/include/source  
-  Modify the sample spl  (1 q 1 port) 
- I changed the parameter for lcore to 1 and nicport to 0 in my case.  
-  cd /toolkit-directory/streamsx.network/samples/SamplePacketDPDKSource
-  make .  (It worked fine up to this stage) 

The job periodically produces error upon submission  and  here is a partial trace log for the job.  

Trace log : 
..
..
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 16 lcore(s)
EAL: invalid parameter for --master-lcore
pure virtual method called
terminate called without an active exception

Usage: dpdk [options]

EAL common options:
  -c COREMASK         Hexadecimal bitmask of cores to run on
  -l CORELIST         List of cores to run on
                      The argument format is <c1>[-c2][,
..
..

**Comment by kanduibm** [comment]
Spec 
Streams Version  = 4.1.0.0
OS = Redhat 6.5 VM
Memory = 16GB

Config kernel module step
02:01.0 Ethernet controller: Intel Corporation 82545EM Gigabit Ethernet Controller (Copper) (rev 01)
[root@residentevil mnt]# /home/streamsadmin/Desktop/dpdk-lib/dpdk-2.2.0//tools/dpdk_nic_bind.py --bind=igb_uio eth0
Error: bind failed for 0000:02:01.0 - Cannot bind to driver igb_uio
Error: unbind failed for 0000:02:01.0 - Cannot open /sys/bus/pci/drivers//unbind
I had to reboot the machine after running the dpdk_nic_bind python tool 
[root@residentevil ~]# /home/streamsadmin/Desktop/dpdk-lib/dpdk-2.2.0/tools/dpdk_nic_bind.py
--status

Network devices using DPDK-compatible driver

<none>
Network devices using kernel driver

0000:02:01.0 '82545EM Gigabit Ethernet Controller (Copper)' if=eth0 drv=e1000 unused= _Active_
Other network devices

[root@residentevil ~] vim /dev/u
uinput   urandom  usbmon0  usbmon1  usbmon2  
[root@residentevil ~] chown root:dpdk /dev/uio0
chown: cannot access `/dev/uio0': No such file or directory

**Comment by engebret** [comment]
Significant updates to this portion of the code have occurred over the past year, so I'm closing this version of the issue.  A new one can be opened as needed if similar problems are still observed.

**Comment by AlecZadikian9001** [comment]
I still see this problem with `dpdk-stable-17.05.1`. I also tried installing just through the `dpdk-setup.sh` script. Got the error both times. Guessing, I just ran `sudo make install` in the root of the DPDK directory after doing that, and it seemed to work.

**Comment by pzrq** [comment]
I found the [documentation (currently `Chapter 39 - Development Kit Build System`)](http://dpdk.org/doc/guides/prog_guide/dev_kit_build_system.html) very useful to understand better about what actually seems to be going on with this build directory concept and how to use the `RTE_SDK` and `RTE_TARGET` environment variables.

It enabled me to work around the errors in the [original post](https://github.com/IBMStreams/streamsx.network/issues/52#issue-152540524) in the context of [megakv](https://github.com/pzrq/megakv) as @cancilla stated in his [follow up comment](https://github.com/IBMStreams/streamsx.network/issues/52#issuecomment-216219322).

I agree with @engebret that this version of the issue can be safely closed and new issues created as needed, especially if [`Chapter 3 - Compiling the DPDK Target from Source`](http://dpdk.org/doc/guides/linux_gsg/build_dpdk.html) will be the authoritative build instructions going forward (it's not clear to me, e.g. via a link from any post on this issue).

**Comment by zxc4561** [comment]
> I still see this problem with `dpdk-stable-17.05.1`. I also tried installing just through the `dpdk-setup.sh` script. Got the error both times. Guessing, I just ran `sudo make install` in the root of the DPDK directory after doing that, and it seemed to work.

Thank you, that worked!
