### ISSUE TITLE
Globalizing the toolkit

### ISSUE THREAD

**Issue by gertmark** [IBMStreams/streamsx.network#67]
Provide log messages for different locales via unique message ids: German (de_DE), French (fr_FR), Italian (it_IT), Spanish (es_ES). Brazilian Portuguese (pt_BR), Japanese (ja_JP), Simplified Chinese (zh_CN), Russian (ru_RU), Traditional Chinese (zh_TW), Korean (ko_KR).

**Comment by markheger** [comment]
The new branch i18n_foundation is intended for this feature.

**Comment by markheger** [comment]
The branch i18n_foundation has been merged to master branch. Toolkit version 3.0.0.
