### ISSUE TITLE
Can someone tell me, how to use these toolkits ?

### ISSUE THREAD

**Issue by toomuchfur** [IBMStreams/streamsx.network#68]
I have my vmware 4.2 and I need to use these toolkits to analyze the network data, compared to wireshark. Can somebody tell me which app should i use or how to install these toolkits to use on the vmware. 
Thank you so much
![unbenannt](https://cloud.githubusercontent.com/assets/23074819/19722353/9b1da34a-9b76-11e6-82b4-24a9cc984464.png)
](url)

**Comment by markheger** [comment]
As pre-requisite I recommend the Streams tutorials:
http://ibmstreams.github.io/tutorials/

To learn more about the Network Toolkit, please have a look at the following post:
https://developer.ibm.com/streamsdev/docs/infosphere-streams-network-toolkit-overview/
