### ISSUE TITLE
 warning: missing braces around initializer

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.network#72]
Has anyone else seen this Warning from the latest 2.8.5 release? I'm getting this when using the Streams 4.2 production version. I took a quick scan of the code, and I don't see anything wrong. Looks like maybe it's related to this compiler bug? http://stackoverflow.com/questions/13746033/how-to-repair-warning-missing-braces-around-initializer 

gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC)  from the QSE

/opt/ibm/InfoSphere_Streams/4.2.0.0/toolkits/com.ibm.streamsx.network/impl/include/./IPv4AddressFunctions.h: In function ‘SPL::rstring com::ibm::streamsx::network::ipv4::convertIPV4AddressNumericToString(SPL::uint32)’:
/opt/ibm/InfoSphere_Streams/4.2.0.0/toolkits/com.ibm.streamsx.network/impl/include/./IPv4AddressFunctions.h:122: warning: missing braces around initializer for ‘com::ibm::streamsx::network::ipv4::convertIPV4AddressNumericToString(SPL::uint32)::textEntry’
/opt/ibm/InfoSphere_Streams/4.2.0.0/toolkits/com.ibm.streamsx.network/impl/include/./IPv4AddressFunctions.h:122: warning: missing braces around initializer for ‘com::ibm::streamsx::network::ipv4::convertIPV4AddressNumericToString(SPL::uint32)::textEntry’
/opt/ibm/InfoSphere_Streams/4.2.0.0/toolkits/com.ibm.streamsx.network/impl/include/./IPv4AddressFunctions.h:122: warning: missing braces around initializer for ‘com::ibm::streamsx::network::ipv4::convertIPV4AddressNumericToString(SPL::uint32)::textEntry’
/opt/ibm/InfoSphere_Streams/4.2.0.0/toolkits/com.ibm.streamsx.network/impl/include/./IPv4AddressFunctions.h:122: warning: missing braces around initializer for ‘com::ibm::streamsx::network::ipv4::convertIPV4AddressNumericToString(SPL::uint32)::textEntry’
/opt/ibm/InfoSphere_Streams/4.2.0.0/toolkits/com.ibm.streamsx.network/impl/include/./IPv4AddressFunctions.h:122: warning: missing braces around initializer for ‘com::ibm::streamsx::network::ipv4::convertIPV4AddressNumericToString(SPL::uint32)::textEntry’
/opt/ibm/InfoSphere_Streams/4.2.0.0/toolkits/com.ibm.streamsx.network/impl/include/./IPv4AddressFunctions.h:122: warning: missing braces around initializer for ‘com::ibm::streamsx::network::ipv4::convertIPV4AddressNumericToString(SPL::uint32)::textEntry’

**Comment by ejpring** [comment]
Not sure which 2.8.5 you're referring to. I have some Docker containers with RHEL 7.3 and Streams 4.2.0.2. They have 'gcc' version 4.8.5 installed, so I tried 'testPacketFileSourceBasic1.sh', which compiles and runs TestPacketFileSourceBasic1.spl, which includes some convertIPV4AddressNumericToString() functions, and I did not get any warnings like this. Here's what the 'gcc' compiler says about itself:

bash> gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

**Comment by Alex-Cook4** [comment]
I ran into this on RHEL 6. With gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC). 

Seems like that is probably the issue. Things seem to still run fine, so I'm happy to close.

**Comment by ejpring** [comment]
OK. I don't have any RHEL/CentOS 6 systems anymore.

When you migrate to RHEL/CentOS 7, one of the changes reduces the size of the kernel by omitting most of the 'locales' in /usr/lib/locale/locale-archive . That may create a problem for Streams, which needs the 'en_US' locale. The workaround for that is to re-install the locales needed. For example, this command will install the locales for English, German, and Spanish:

sudo rpm -Uvh --replacepkgs -D _install_langs=":en:de:es" http://mirror.centos.org/centos/7/updates/x86_64/Packages/$( rpm -q glibc-common ).rpm

**Comment by GudrunKa** [comment]
This problem also occurs when testing the network toolkit in the Streams V4.2 QSE which has Cent OS 6.8 as OS. At least for the QSE this problem should be solved

**Comment by ejpring** [comment]
I'm not sure whether this is an instance of Gcc bug 53119 (see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53119 ). At least, the array in this case is not multi-dimensional, and its initializer is not "{0}". So I think it would be wrong to add extra braces around the initializer.

My preference would be to upgrade the QSE virtual machines to RHEL/CentOS 7, but that's not my decision. So I think the least disruptive workaround might be to add:

#pragma GCC diagnostic ignored "-Wno-missing-braces"

to .../impl/include/IPv4AddressFunctions.h .

However, I don't have any RHEL/CentOS 6 machines anymore, so I can't test that.

**Comment by ejpring** [comment]
I've pushed a workaround to this fork of the network toolkit:

https://github.com/ejpring/streamsx.network

Can one of you with a RHEL/CentOS 6 system try it and report whether it suppresses the warning message?

**Comment by GudrunKa** [comment]
We have tested the workaround with CentOS 6.8 and RHEL 6.7 and it does not suppress the warnings.

**Comment by ejpring** [comment]
OK, let's try a different pragma. Can you pull https://github.com/ejpring/streamsx.network again and re-test ?

**Comment by GudrunKa** [comment]
The workaround #pragma GCC diagnostic ignored "-Wmissing-braces"  was successful in both OS versions.

**Comment by ejpring** [comment]
OK, let's go with that one then.

**Comment by markheger** [comment]
Workaround is required for DNSPacketFlattener.h, too
