### ISSUE TITLE
Wrong default value for pcap filename in samples

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.network#74]
Sample applications have a composite parameter to specify the pcap file. 
for instance:
expression<rstring> $pcapFilename: getSubmissionTimeValue("pcapFilename", "../../SampleNetworkToolkitData/sample_dns+dhcp.pcap" );
The default values needs to be changed to the right path:
"../../SampleNetworkToolkitData/data/sample_dns+dhcp.pcap"
The files are located in the **data** of the SampleNetworkToolkitData project.
This would help using the samples in StreamsStudio.

**Comment by ejpring** [comment]
I agree. I'll clean this up.

**Comment by markheger** [comment]
fixed in 3.0.0
