### ISSUE TITLE
Sample TestIPAdressLocationBasicIPv6 does not work

### ISSUE THREAD

**Issue by GudrunKa** [IBMStreams/streamsx.network#77]
The LocatedPacketStream does not deliver any output, since the filter criteria of the IPAddressLocation operator do not fit to the sample pcap data.
When the filter is changed to 'or' instead of 'and' for the locationCityNames of ipSourceAddress and ipDestinationAddress, some output is delivered.

**Comment by ejpring** [comment]
The LocatedPacketStream output looks correct to me, running either in Studio or with BASH scripts. Are you sure you ran .../script/getGeographyData.sh before running the sample applications? There should be a bunch of .../data/www.maxmind.com/GeoLite2-City-XXXX.csv files in your workspace.

**Comment by GudrunKa** [comment]
Running the sample with the script as well as in StreamsStudio, the output file debug.TestIPAddressLocationBasicIPv6.LocatedPacketStream.out is created, but remains empty. That's correct when I consider the input data and the current filter condition. But in order to demonstrate how it works, it would be better to have some lines in the output file. 
When I change the filter, as proposed above, then I get some output.

**Comment by ejpring** [comment]
I think the problem here is that 'sample_locations_ipv6_only.pcap' is not very good. If you can contribute a PCAP recording of IPv6 traffic that has fewer packets with errors and more packets with real addresses, it would be appreciated.

**Comment by GudrunKa** [comment]
I found some pcap files with IPv6 traffic but they also don't bring any output with the locationCityNames function. Therefore I think, the current sample file should be kept and the filter should be changed as proposed above ('or' instead of 'and') so that real addresses that can be mapped ( from 39 of 410 frames) are output into the file.  That at least demonstrates the functionality.

**Comment by ejpring** [comment]
I'm not particularly concerned about demonstrating the functionality of the operator; the sample IPv4 traffic does that.  I am curious to learn more about the problem with IPv6 traffic. Is the problem that IBM does not have good samples of real IPv6 traffic, or, is the problem that MaxMind does not have good coverage in its IPv6-to-location data? 

In any event, I don't think there's any urgency about this. Until a customer complains, its just a theoretical problem. When and if a customer does complain, we'll get some samples of real IPv6 traffic from them, and do a proper analysis...

**Comment by GudrunKa** [comment]
I think that's a problem of the MaxMind data that I could use. I only had the GeoLite2 data which can be downloaded for free. The GeoIP2 data which can be purchased are much more accurate. 
Again, to demonstrate the mapping of IP addresses to locations, I would change the filter of the sample to have at least some output, and not an empty file.

**Comment by markheger** [comment]
The value of the outputFilters parameter for the IPAddressLocation operator in the TestIPAddressLocationBasicIPv6 sample should be changed to:
outputFilters: locationCityName(ipSourceAddress)!="" || locationCityName(ipDestinationAddress)!="";
