### ISSUE TITLE
Samples TestNetflowMessageParserBasic and -FullVersion5 do not work

### ISSUE THREAD

**Issue by GudrunKa** [IBMStreams/streamsx.network#78]
The samples TestNetflowMessageParserBasic and TestNetflowMessageParserFullVersion5 do not work since the port in the inputFilter of the PacketFileSource operator is set to 2055 instead of 9500.

**Comment by ejpring** [comment]
I agree the SPL files should use the same parameters as the SH files.

**Comment by GudrunKa** [comment]
With version 3.0.0 of the toolkit this problem is solved.
