### ISSUE TITLE
TestPacketContentAssembler samples do not work in StreamsStudio in Streams V4.2 QSE

### ISSUE THREAD

**Issue by GudrunKa** [IBMStreams/streamsx.network#79]
The samples TestPacketContentAssemblerEvents, ~FlowsAndFiles, and ~Full do not work in StreamsStudio since the input files mentioned in the SPL files are not delivered in the product. With the scripts the samples work since the submission time parameters are set to existing files.

**Comment by ejpring** [comment]
I agree the SPL files should default to the parameters in the SH files
