### ISSUE TITLE
Sample import does not work in Streams versions < V4.2

### ISSUE THREAD

**Issue by GudrunKa** [IBMStreams/streamsx.network#81]
When trying to use the network toolkit as additional toolkit in a Streams version where it is not part of the product, i.e. a version < 4.2, it was not possible to import and execute the samples in StreamsStudio. 
If a .project file would be delivered with the toolkit it would at least be possible to import them as existing projects.

**Comment by GudrunKa** [comment]
My mistake. There were .project files for each sample so that I could import them as existing projects.

**Comment by GudrunKa** [comment]
The sample TestPacketDPDKSource has no .project file. Therefore it can neither be imported as sample nor as existing project.

**Comment by ejpring** [comment]
The DPDK-related operators and their sample applications depend upon specialized hardware and software, and extensive system configuration. They are not suitable for use in Studio.

**Comment by GudrunKa** [comment]
Why is it not possible to execute TestPacketDPDKSource in StreamsStudio when I have fulfilled all the mentioned dependencies? What exactly is the problem?

**Comment by markheger** [comment]
Delivered with #100
