### ISSUE TITLE
Purpose of 'static-link' option for PacketLiveSource operator

### ISSUE THREAD

**Issue by GudrunKa** [IBMStreams/streamsx.network#82]
In the KC of Streams V4.2 the following is mentioned: 
'the SPL source must be compiled with the '--static-link' option.
This option is no more supported in Streams V4.2. Why it should be used and why does the operator work in V4.2 without this option?

**Comment by ejpring** [comment]
In Streams 4.1, the --static-link option of the 'sc' command was required for applications that use the PacketLiveSource operator to link dependent system libraries into SAB bundles.  

In Streams 4.2, the 'sc' command always links dependent system libraries into SAB bundles, so the --static-link option is not needed, but does no harm if specified.

**Comment by GudrunKa** [comment]
Issue will be re-opened if that would cause any problems in future.
