### ISSUE TITLE
TestPacketFileSourceInputStream does not work with the default pcapDirectory in StreamsStudio

### ISSUE THREAD

**Issue by GudrunKa** [IBMStreams/streamsx.network#93]
The sample TestPacketFileSourceInputStream has a default value for the pcapDirectory in which the pcap files shall be scanned: 'data'. When launching the application in StreamsStudio, the following happens: CDISR5030E: An exception occurred during the execution of the FilepathStream operator. The exception is: The data directory does not exist. 
Additionally, when executing the script with a working pcapDirectory, the timeoutInterval for the PE shutdown is too low. It should be set to a value (30.0 seconds) so that the tester can see that output is generated.

**Comment by markheger** [comment]
data as default value results in <data-dir>/data hence the default value needs to be changed to "." for the pcapDirectory composite parameter
