### ISSUE TITLE
Operator DNSPacketDPDKSource documentation

### ISSUE THREAD

**Issue by GudrunKa** [IBMStreams/streamsx.network#97]
As part of the product the network toolkit will be available in the toolkit directory of the product install directory. Therefore it is not necessary to mention in the documentation of the DNSPacketDPDKSource operator that the network toolkit should be retrieved from github. The following sentence should be deleted:

"If you don't already have the Streams network toolkit, get it by typing these commands at a prompt:
    bash&gt; cd $HOME/git
    bash&gt; git clone git@github.com:ejpring/streamsx.network.git"

Further references to github should also be removed.

Additionally some sections seem to be incomplete. They should be filled:
"# bind 'Mellanox' ethernet device to DPDK

To be done ..."    and 

"# unbind 'Mellanox' ethernet device from DPDK

To be done ..."

**Comment by markheger** [comment]
DNSPacketDPDKSource.xml looks fine in 3.0.3
